sonar.projectKey=Uriel4560_UrbanFlow

sonar.organization=uriel4560

sonar.host.url=https://sonarcloud.io

sonar.sources=src

sonar.java.binaries=target/classes

sonar.token=7bfc5a5e263a0c014df8235ecc5a785ea4721742