name: CI Spring Boot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Hacer ejecutable mvnw
        run: chmod +x mvnw

      - name: Ejecutar pruebas
        run: ./mvnw test

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw -B sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=uriel4560 -Dsonar.projectKey=Uriel4560_UrbanFlow -Dsonar.login=${{ secrets.SONAR_TOKEN }}